export const ACTION_TYPES = {
    GET_LIST_TOPIC: 'GET_LIST_TOPIC',
    LOGIN: 'LOGIN',
    LOADING: 'LOADING',
    PROFILE: "PROFILE",
    SHOW_SNACKBAR: 'SHOW_SNACKBAR',
    AVATAR: 'AVATAR',
}
export const DROPDOWN_CLASS = {
    GET_LIST_CLASS: 'GET_LIST_CLASS',
}